FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY pitch.html /usr/share/nginx/html/pitch.html
COPY investors.html /usr/share/nginx/html/investors.html
COPY cps.html /usr/share/nginx/html/cps.html
COPY privacy.html /usr/share/nginx/html/privacy.html
COPY terms.html /usr/share/nginx/html/terms.html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
