//! Internal PKI — node certificate provisioning.
//!
//! Provides a self-contained CA that issues short-lived TLS certificates for
//! P2P nodes, eliminating the dependency on an external CA.
//!
//! # Environment variables
//!
//! | Variable | Description |
//! |----------|-------------|
//! | `TLS_CA_CERT_PATH` | Path to the CA certificate PEM file (for distribution) |
//! | `TLS_CA_KEY_PATH`  | Path to the CA private key PEM file (for signing)      |
//!
//! # Design note
//!
//! When loading an existing CA from disk, this module reconstructs the rcgen
//! `Certificate` from the persisted key using a fixed Common Name
//! (`INTERNAL_CA_CN`). For the chain to validate, the CA cert on disk must have
//! been generated by `NodeCaConfig::generate` (which uses the same CN and key).
//!
//! # Example
//!
//! ```no_run
//! use rust_bc::pki::{NodeCaConfig, sign_node_cert};
//!
//! let ca = NodeCaConfig::from_env().unwrap();
//! let cert = sign_node_cert("node-1", &ca, 365).unwrap();
//! cert.save(
//!     std::path::Path::new("/etc/tls/node.crt"),
//!     std::path::Path::new("/etc/tls/node.key"),
//! ).unwrap();
//! ```

use rcgen::{BasicConstraints, CertificateParams, CustomExtension, DnType, IsCa, KeyPair};
use rustls::pki_types::CertificateDer;
use std::path::Path;

/// Common Name used for all internally-generated CA certificates.
pub const INTERNAL_CA_CN: &str = "Rust-BC Internal CA";

#[allow(dead_code)]
/// CA certificate validity (10 years from a fixed epoch).
const CA_NOT_BEFORE: time::OffsetDateTime = time::macros::datetime!(2024-01-01 0:00 UTC);
#[allow(dead_code)]
const CA_NOT_AFTER: time::OffsetDateTime = time::macros::datetime!(2034-01-01 0:00 UTC);

// ── Errors ─────────────────────────────────────────────────────────────────

#[derive(Debug, thiserror::Error)]
pub enum PkiError {
    #[error("rcgen error: {0}")]
    Rcgen(#[from] rcgen::Error),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[allow(dead_code)]
    #[error("TLS_CA_CERT_PATH must be set for PKI provisioning")]
    MissingCaCert,
    #[error("TLS_CA_KEY_PATH must be set for PKI provisioning")]
    MissingCaKey,
    #[error("cannot read file '{0}': {1}")]
    ReadFile(String, #[source] std::io::Error),
}

// ── IssuedNodeCert ─────────────────────────────────────────────────────────

#[allow(dead_code)]
/// A node certificate issued by the internal CA.
pub struct IssuedNodeCert {
    /// DER-encoded signed certificate (ready for use with rustls).
    pub cert_der: CertificateDer<'static>,
    /// PEM-encoded certificate (for writing to disk or embedding in configs).
    pub cert_pem: String,
    /// PEM-encoded private key.
    pub key_pem: String,
}

impl IssuedNodeCert {
    #[allow(dead_code)]
    /// Write cert and key to the given paths as PEM files.
    pub fn save(&self, cert_path: &Path, key_path: &Path) -> Result<(), PkiError> {
        std::fs::write(cert_path, self.cert_pem.as_bytes())?;
        std::fs::write(key_path, self.key_pem.as_bytes())?;
        Ok(())
    }
}

// ── NodeCaConfig ───────────────────────────────────────────────────────────

/// An internal CA that can sign P2P node certificates.
pub struct NodeCaConfig {
    #[allow(dead_code)]
    ca_cert: rcgen::Certificate,
    ca_key: KeyPair,
}

impl std::fmt::Debug for NodeCaConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("NodeCaConfig")
            .field("ca_cn", &INTERNAL_CA_CN)
            .finish_non_exhaustive()
    }
}

impl NodeCaConfig {
    /// Access the CA certificate (for CRL signing, cert issuance).
    pub fn cert(&self) -> &rcgen::Certificate {
        &self.ca_cert
    }

    /// Access the CA key pair (for CRL signing, cert issuance).
    pub fn key(&self) -> &KeyPair {
        &self.ca_key
    }

    #[allow(dead_code)]
    /// Load a CA from PEM key file, reconstructing the rcgen signing cert.
    ///
    /// The `cert_path` file is validated (must be readable) but its content is
    /// used only for distribution — the signing cert is rebuilt from the key
    /// using [`INTERNAL_CA_CN`], which must match how the CA was originally
    /// generated.
    pub fn from_pem_files(cert_path: &Path, key_path: &Path) -> Result<Self, PkiError> {
        // Validate both paths are readable.
        let _cert_pem = std::fs::read_to_string(cert_path)
            .map_err(|e| PkiError::ReadFile(cert_path.display().to_string(), e))?;
        let key_pem = std::fs::read_to_string(key_path)
            .map_err(|e| PkiError::ReadFile(key_path.display().to_string(), e))?;
        let ca_key = KeyPair::from_pem(&key_pem)?;
        let ca_cert = make_ca_cert_params()?.self_signed(&ca_key)?;
        Ok(Self { ca_cert, ca_key })
    }

    /// Load from `TLS_CA_CERT_PATH` + `TLS_CA_KEY_PATH` environment variables.
    pub fn from_env() -> Result<Self, PkiError> {
        let cert_path = std::env::var("TLS_CA_CERT_PATH").map_err(|_| PkiError::MissingCaCert)?;
        let key_path = std::env::var("TLS_CA_KEY_PATH").map_err(|_| PkiError::MissingCaKey)?;
        Self::from_pem_files(Path::new(&cert_path), Path::new(&key_path))
    }

    #[allow(dead_code)]
    /// Generate a new self-signed CA in memory.
    ///
    /// Returns `(NodeCaConfig, cert_pem, key_pem)` so the caller can persist
    /// the cert and key to disk for future reloads and for distribution to
    /// peer nodes.
    pub fn generate() -> Result<(Self, String, String), PkiError> {
        let ca_key = KeyPair::generate()?;
        let ca_cert = make_ca_cert_params()?.self_signed(&ca_key)?;
        let cert_pem = ca_cert.pem();
        let key_pem = ca_key.serialize_pem();
        Ok((Self { ca_cert, ca_key }, cert_pem, key_pem))
    }
}

/// Build a DER-encoded certificatePolicies extension (OID 2.5.29.32).
///
/// Contains a single PolicyInformation with a CPS URI qualifier.
/// Structure: SEQUENCE { SEQUENCE { OID, SEQUENCE { SEQUENCE { OID, IA5String } } } }
pub fn certificate_policies_extension(policy_oid: &str, cps_uri: &str) -> CustomExtension {
    let policy_oid_parts: Vec<u64> = policy_oid
        .split('.')
        .filter_map(|s| s.parse().ok())
        .collect();
    let cps_qualifier_oid: &[u8] = &[0x06, 0x08, 0x2B, 0x06, 0x01, 0x05, 0x05, 0x07, 0x02, 0x01];

    let policy_oid_der = encode_oid_der(&policy_oid_parts);
    let uri_bytes = cps_uri.as_bytes();
    let uri_der = encode_ia5string_der(uri_bytes);

    let qualifier_info = encode_sequence(&[cps_qualifier_oid, &uri_der]);
    let qualifiers = encode_sequence(&[&qualifier_info]);
    let policy_info = encode_sequence(&[&policy_oid_der, &qualifiers]);
    let content = encode_sequence(&[&policy_info]);

    CustomExtension::from_oid_content(&[2, 5, 29, 32], content)
}

fn encode_oid_der(parts: &[u64]) -> Vec<u8> {
    if parts.len() < 2 {
        return vec![0x06, 0x00];
    }
    let mut body = vec![(parts[0] * 40 + parts[1]) as u8];
    for &p in &parts[2..] {
        if p < 128 {
            body.push(p as u8);
        } else {
            let mut bytes = Vec::new();
            let mut val = p;
            bytes.push((val & 0x7F) as u8);
            val >>= 7;
            while val > 0 {
                bytes.push((val & 0x7F) as u8 | 0x80);
                val >>= 7;
            }
            bytes.reverse();
            body.extend(bytes);
        }
    }
    let mut out = vec![0x06];
    encode_length(&mut out, body.len());
    out.extend(body);
    out
}

fn encode_ia5string_der(s: &[u8]) -> Vec<u8> {
    let mut out = vec![0x16];
    encode_length(&mut out, s.len());
    out.extend(s);
    out
}

fn encode_sequence(items: &[&[u8]]) -> Vec<u8> {
    let total: usize = items.iter().map(|i| i.len()).sum();
    let mut out = vec![0x30];
    encode_length(&mut out, total);
    for item in items {
        out.extend(*item);
    }
    out
}

fn encode_length(out: &mut Vec<u8>, len: usize) {
    if len < 128 {
        out.push(len as u8);
    } else if len < 256 {
        out.push(0x81);
        out.push(len as u8);
    } else {
        out.push(0x82);
        out.push((len >> 8) as u8);
        out.push(len as u8);
    }
}

#[allow(dead_code)]
/// Build `CertificateParams` for the internal CA (fixed CN and validity).
fn make_ca_cert_params() -> Result<CertificateParams, PkiError> {
    let mut params = CertificateParams::new(vec![])?;
    params
        .distinguished_name
        .push(DnType::CommonName, INTERNAL_CA_CN);
    params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
    params.not_before = CA_NOT_BEFORE;
    params.not_after = CA_NOT_AFTER;
    params
        .custom_extensions
        .push(certificate_policies_extension(
            crate::pki_policy::CP_OID,
            "https://goya.cl/pki/cp",
        ));
    Ok(params)
}

// ── CA Hierarchy (Root + Intermediate) ────────────────────────────────────

/// Common Name for the intermediate CA.
pub const INTERMEDIATE_CA_CN: &str = "Goya Ledger Intermediate CA";

/// Two-tier CA: offline root + operational intermediate.
///
/// The root CA signs the intermediate. The intermediate signs node certs
/// and CRLs. Root key should be stored offline in production.
pub struct CaHierarchy {
    root: NodeCaConfig,
    root_cert_pem: String,
    intermediate: NodeCaConfig,
    intermediate_cert_pem: String,
}

impl std::fmt::Debug for CaHierarchy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CaHierarchy")
            .field("root_cn", &INTERNAL_CA_CN)
            .field("intermediate_cn", &INTERMEDIATE_CA_CN)
            .finish_non_exhaustive()
    }
}

impl CaHierarchy {
    /// Generate a new two-tier CA hierarchy in memory.
    pub fn generate() -> Result<Self, PkiError> {
        let root_key = KeyPair::generate()?;
        let root_cert = make_ca_cert_params()?.self_signed(&root_key)?;
        let root_cert_pem = root_cert.pem();

        let intermediate_key = KeyPair::generate()?;
        let intermediate_cert_params = make_intermediate_params()?;
        let intermediate_cert =
            intermediate_cert_params.signed_by(&intermediate_key, &root_cert, &root_key)?;
        let intermediate_cert_pem = der_to_pem_cert(intermediate_cert.der().as_ref());

        Ok(Self {
            root: NodeCaConfig {
                ca_cert: root_cert,
                ca_key: root_key,
            },
            root_cert_pem,
            intermediate: NodeCaConfig {
                ca_cert: intermediate_cert,
                ca_key: intermediate_key,
            },
            intermediate_cert_pem,
        })
    }

    /// The root CA (offline — use only for signing intermediates).
    pub fn root(&self) -> &NodeCaConfig {
        &self.root
    }

    /// The intermediate CA (operational — signs node certs, CRLs, OCSP).
    pub fn intermediate(&self) -> &NodeCaConfig {
        &self.intermediate
    }

    /// Root CA certificate PEM.
    pub fn root_cert_pem(&self) -> &str {
        &self.root_cert_pem
    }

    /// Intermediate CA certificate PEM.
    pub fn intermediate_cert_pem(&self) -> &str {
        &self.intermediate_cert_pem
    }

    /// Full chain PEM (intermediate + root) for TLS configuration.
    pub fn chain_pem(&self) -> String {
        format!("{}{}", self.intermediate_cert_pem, self.root_cert_pem)
    }

    /// Issue a node certificate signed by the intermediate CA.
    pub fn sign_node_cert(&self, node_id: &str, ttl_days: u32) -> Result<IssuedNodeCert, PkiError> {
        sign_node_cert(node_id, &self.intermediate, ttl_days)
    }
}

/// Build `CertificateParams` for the intermediate CA.
fn make_intermediate_params() -> Result<CertificateParams, PkiError> {
    let mut params = CertificateParams::new(vec![])?;
    params
        .distinguished_name
        .push(DnType::CommonName, INTERMEDIATE_CA_CN);
    params.is_ca = IsCa::Ca(BasicConstraints::Constrained(0));
    let now = time::OffsetDateTime::now_utc();
    params.not_before = now;
    params.not_after = now + time::Duration::days(365 * 5);
    params
        .custom_extensions
        .push(certificate_policies_extension(
            crate::pki_policy::CP_OID,
            "https://goya.cl/pki/cp",
        ));
    Ok(params)
}

/// Build raw DER content for QCStatements (EN 319 412-5).
/// Returns the SEQUENCE OF QCStatement bytes without the extension wrapper.
pub fn build_qc_statements_der(profile: crate::pki_policy::CertProfileType) -> Vec<u8> {
    let compliance_oid = parse_oid_str(crate::pki_policy::QC_COMPLIANCE_OID);
    let compliance_oid_der = encode_oid_der(&compliance_oid);
    let qc_compliance = encode_sequence(&[&compliance_oid_der]);

    let type_oid = parse_oid_str(crate::pki_policy::QC_TYPE_OID);
    let type_oid_der = encode_oid_der(&type_oid);

    let qc_type_value_oid = match profile {
        crate::pki_policy::CertProfileType::NaturalPerson => crate::pki_policy::QCT_ESIGN_OID,
        crate::pki_policy::CertProfileType::LegalPerson => crate::pki_policy::QCT_ESEAL_OID,
        crate::pki_policy::CertProfileType::WebAuthentication => crate::pki_policy::QCT_WEB_OID,
    };
    let qc_type_value_der = encode_oid_der(&parse_oid_str(qc_type_value_oid));
    let qc_type_info = encode_sequence(&[&qc_type_value_der]);
    let qc_type = encode_sequence(&[&type_oid_der, &qc_type_info]);

    encode_sequence(&[&qc_compliance, &qc_type])
}

/// Build a DER-encoded QCStatements extension (OID 1.3.6.1.5.5.7.1.3).
///
/// EN 319 412-5: contains QcCompliance + QcType statements.
/// QCStatements ::= SEQUENCE OF QCStatement
/// QCStatement  ::= SEQUENCE { statementId OID, statementInfo ANY OPTIONAL }
pub fn qc_statements_extension(profile: crate::pki_policy::CertProfileType) -> CustomExtension {
    let content = build_qc_statements_der(profile);
    // id-pe-qcStatements 1.3.6.1.5.5.7.1.3
    CustomExtension::from_oid_content(&[1, 3, 6, 1, 5, 5, 7, 1, 3], content)
}

fn parse_oid_str(oid: &str) -> Vec<u64> {
    oid.split('.').filter_map(|s| s.parse().ok()).collect()
}

// ── sign_node_cert ─────────────────────────────────────────────────────────

#[allow(dead_code)]
/// Generate a new ECDSA P-256 key pair and issue a TLS certificate for
/// `node_id`, signed by `ca`.
///
/// The certificate carries `node_id` as both the Common Name and a DNS SAN,
/// and is valid for `ttl_days` days from the current time.
pub fn sign_node_cert(
    node_id: &str,
    ca: &NodeCaConfig,
    ttl_days: u32,
) -> Result<IssuedNodeCert, PkiError> {
    let key_pair = KeyPair::generate()?;

    let mut params = CertificateParams::new(vec![node_id.to_string()])?;
    params.distinguished_name.push(DnType::CommonName, node_id);
    params.is_ca = IsCa::NoCa;
    let now = time::OffsetDateTime::now_utc();
    params.not_before = now;
    params.not_after = now + time::Duration::days(i64::from(ttl_days));
    params
        .custom_extensions
        .push(certificate_policies_extension(
            crate::pki_policy::CP_OID,
            "https://goya.cl/pki/cp",
        ));

    let cert = params.signed_by(&key_pair, &ca.ca_cert, &ca.ca_key)?;
    let cert_der = cert.der().clone();
    let cert_pem = der_to_pem_cert(cert_der.as_ref());
    let key_pem = key_pair.serialize_pem();

    Ok(IssuedNodeCert {
        cert_der,
        cert_pem,
        key_pem,
    })
}

// ── renew_node_cert ───────────────────────────────────────────────────────

/// Renew a node certificate: same identity (node_id), fresh key pair,
/// new validity period. The caller must revoke the old certificate via
/// LifecycleManager::revoke_and_publish_crl before calling this.
pub fn renew_node_cert(
    node_id: &str,
    ca: &NodeCaConfig,
    ttl_days: u32,
) -> Result<IssuedNodeCert, PkiError> {
    sign_node_cert(node_id, ca, ttl_days)
}

// ── provision_node_cert_if_absent ──────────────────────────────────────────

#[allow(dead_code)]
/// If `cert_path` and `key_path` do not both exist, generate a new node
/// certificate signed by the CA from environment variables and write them to
/// disk.
///
/// Returns `true` if a new cert was provisioned, `false` if both files were
/// already present (no action taken).
///
/// # Environment variables required
/// `TLS_CA_CERT_PATH` and `TLS_CA_KEY_PATH` must be set.
pub fn provision_node_cert_if_absent(
    node_id: &str,
    cert_path: &Path,
    key_path: &Path,
    ttl_days: u32,
) -> Result<bool, PkiError> {
    if cert_path.exists() && key_path.exists() {
        return Ok(false);
    }
    let ca = NodeCaConfig::from_env()?;
    let issued = sign_node_cert(node_id, &ca, ttl_days)?;
    issued.save(cert_path, key_path)?;
    Ok(true)
}

// ── PEM helpers ────────────────────────────────────────────────────────────

#[allow(dead_code)]
/// Encodes DER bytes as a PEM CERTIFICATE block (no external crate needed).
fn der_to_pem_cert(der: &[u8]) -> String {
    let b64 = base64_encode(der);
    let mut out = String::from("-----BEGIN CERTIFICATE-----\n");
    for chunk in b64.as_bytes().chunks(64) {
        // SAFETY: base64_encode only emits ASCII bytes from the table or '='.
        out.push_str(unsafe { std::str::from_utf8_unchecked(chunk) });
        out.push('\n');
    }
    out.push_str("-----END CERTIFICATE-----\n");
    out
}

#[allow(dead_code)]
fn base64_encode(data: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = Vec::with_capacity(data.len().div_ceil(3) * 4);
    for chunk in data.chunks(3) {
        let b0 = chunk[0] as usize;
        let b1 = if chunk.len() > 1 {
            chunk[1] as usize
        } else {
            0
        };
        let b2 = if chunk.len() > 2 {
            chunk[2] as usize
        } else {
            0
        };
        out.push(TABLE[(b0 >> 2) & 0x3F]);
        out.push(TABLE[((b0 << 4) | (b1 >> 4)) & 0x3F]);
        out.push(if chunk.len() > 1 {
            TABLE[((b1 << 2) | (b2 >> 6)) & 0x3F]
        } else {
            b'='
        });
        out.push(if chunk.len() > 2 {
            TABLE[b2 & 0x3F]
        } else {
            b'='
        });
    }
    // SAFETY: all bytes are ASCII from TABLE or '='.
    unsafe { String::from_utf8_unchecked(out) }
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::Mutex;
    use tempfile::NamedTempFile;

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    // ── helpers ────────────────────────────────────────────────────────────

    fn make_ca() -> (NodeCaConfig, String, String) {
        NodeCaConfig::generate().unwrap()
    }

    fn write_temp(content: &str) -> NamedTempFile {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f.flush().unwrap();
        f
    }

    // ── base64 / PEM ───────────────────────────────────────────────────────

    #[test]
    fn base64_encode_empty() {
        assert_eq!(base64_encode(b""), "");
    }

    #[test]
    fn base64_encode_known_values() {
        assert_eq!(base64_encode(b"Man"), "TWFu");
        assert_eq!(base64_encode(b"Ma"), "TWE=");
        assert_eq!(base64_encode(b"M"), "TQ==");
    }

    #[test]
    fn der_to_pem_cert_has_correct_headers() {
        let pem = der_to_pem_cert(b"hello");
        assert!(pem.starts_with("-----BEGIN CERTIFICATE-----\n"));
        assert!(pem.ends_with("-----END CERTIFICATE-----\n"));
    }

    #[test]
    fn der_to_pem_cert_is_loadable_by_rustls_pemfile() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-test", &ca, 90).unwrap();
        let pem = issued.cert_pem.clone();

        let mut reader = std::io::BufReader::new(pem.as_bytes());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(certs.len(), 1);
        assert_eq!(certs[0].as_ref(), issued.cert_der.as_ref());
    }

    // ── NodeCaConfig::generate ─────────────────────────────────────────────

    #[test]
    fn generate_ca_produces_valid_pem() {
        let (_, cert_pem, key_pem) = make_ca();
        assert!(cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(key_pem.contains("BEGIN"));
    }

    // ── NodeCaConfig::from_pem_files ───────────────────────────────────────

    #[test]
    fn from_pem_files_loads_generated_ca() {
        let (_, cert_pem, key_pem) = make_ca();
        let cert_file = write_temp(&cert_pem);
        let key_file = write_temp(&key_pem);
        let result = NodeCaConfig::from_pem_files(cert_file.path(), key_file.path());
        assert!(result.is_ok(), "{result:?}");
    }

    #[test]
    fn from_pem_files_fails_with_missing_cert() {
        let (_, _, key_pem) = make_ca();
        let key_file = write_temp(&key_pem);
        let result =
            NodeCaConfig::from_pem_files(Path::new("/nonexistent/ca.pem"), key_file.path());
        assert!(matches!(result, Err(PkiError::ReadFile(..))));
    }

    #[test]
    fn from_pem_files_fails_with_missing_key() {
        let (_, cert_pem, _) = make_ca();
        let cert_file = write_temp(&cert_pem);
        let result =
            NodeCaConfig::from_pem_files(cert_file.path(), Path::new("/nonexistent/ca.key"));
        assert!(matches!(result, Err(PkiError::ReadFile(..))));
    }

    // ── NodeCaConfig::from_env ─────────────────────────────────────────────

    #[test]
    fn from_env_fails_without_ca_cert_var() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");
        let result = NodeCaConfig::from_env();
        assert!(matches!(result, Err(PkiError::MissingCaCert)));
    }

    #[test]
    fn from_env_fails_without_ca_key_var() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, _) = make_ca();
        let cert_file = write_temp(&cert_pem);
        std::env::set_var("TLS_CA_CERT_PATH", cert_file.path());
        std::env::remove_var("TLS_CA_KEY_PATH");
        let result = NodeCaConfig::from_env();
        std::env::remove_var("TLS_CA_CERT_PATH");
        assert!(matches!(result, Err(PkiError::MissingCaKey)));
    }

    #[test]
    fn from_env_succeeds_with_valid_vars() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, key_pem) = make_ca();
        let cert_file = write_temp(&cert_pem);
        let key_file = write_temp(&key_pem);
        std::env::set_var("TLS_CA_CERT_PATH", cert_file.path());
        std::env::set_var("TLS_CA_KEY_PATH", key_file.path());
        let result = NodeCaConfig::from_env();
        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");
        assert!(result.is_ok(), "{result:?}");
    }

    // ── sign_node_cert ─────────────────────────────────────────────────────

    #[test]
    fn sign_node_cert_returns_non_empty_cert_and_key() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-1", &ca, 365).unwrap();
        assert!(!issued.cert_der.as_ref().is_empty());
        assert!(issued.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(issued.key_pem.contains("BEGIN"));
    }

    #[test]
    fn sign_node_cert_chains_to_ca() {
        // Verify that the issued cert's chain validates against the CA in WebPKI.
        let (ca, cert_pem, _) = make_ca();
        let ca_der = {
            let mut reader = std::io::BufReader::new(cert_pem.as_bytes());
            let der = rustls_pemfile::certs(&mut reader).next().unwrap().unwrap();
            der
        };

        let issued = sign_node_cert("node-chain-test", &ca, 365).unwrap();

        // Add CA cert to a root store — must succeed (CA cert is valid).
        let mut root_store = rustls::RootCertStore::empty();
        root_store.add(ca_der).unwrap();

        // Build a client verifier that trusts our CA: if the CA cert is
        // accepted, leaf certs signed by the same key will pass WebPKI chain
        // validation (signature + issuer DN match).
        use rustls::server::WebPkiClientVerifier;
        let verifier = WebPkiClientVerifier::builder(std::sync::Arc::new(root_store)).build();
        assert!(verifier.is_ok(), "CA cert accepted by WebPKI root store");
        // The leaf cert DER must be non-empty and parseable.
        assert!(!issued.cert_der.as_ref().is_empty());
    }

    #[test]
    fn sign_node_cert_with_zero_ttl_does_not_panic() {
        let (ca, _, _) = make_ca();
        let result = sign_node_cert("node-zero-ttl", &ca, 0);
        assert!(result.is_ok());
    }

    #[test]
    fn sign_node_cert_different_keys_per_call() {
        let (ca, _, _) = make_ca();
        let c1 = sign_node_cert("node-a", &ca, 30).unwrap();
        let c2 = sign_node_cert("node-b", &ca, 30).unwrap();
        assert_ne!(
            c1.key_pem, c2.key_pem,
            "each call must generate a fresh key pair"
        );
    }

    // ── IssuedNodeCert::save ───────────────────────────────────────────────

    #[test]
    fn save_writes_readable_pem_files() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-save", &ca, 365).unwrap();

        let cert_file = NamedTempFile::new().unwrap();
        let key_file = NamedTempFile::new().unwrap();
        issued.save(cert_file.path(), key_file.path()).unwrap();

        let cert_bytes = std::fs::read(cert_file.path()).unwrap();
        let mut reader = std::io::BufReader::new(cert_bytes.as_slice());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(certs.len(), 1);

        let key_bytes = std::fs::read(key_file.path()).unwrap();
        let mut kreader = std::io::BufReader::new(key_bytes.as_slice());
        let key = rustls_pemfile::private_key(&mut kreader).unwrap();
        assert!(key.is_some());
    }

    // ── provision_node_cert_if_absent ──────────────────────────────────────

    #[test]
    fn provision_skips_when_both_files_exist() {
        let cert_file = NamedTempFile::new().unwrap();
        let key_file = NamedTempFile::new().unwrap();
        let provisioned =
            provision_node_cert_if_absent("node", cert_file.path(), key_file.path(), 365).unwrap();
        assert!(!provisioned);
    }

    #[test]
    fn provision_creates_cert_and_key_when_both_absent() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, key_pem) = make_ca();
        let ca_cert_file = write_temp(&cert_pem);
        let ca_key_file = write_temp(&key_pem);
        std::env::set_var("TLS_CA_CERT_PATH", ca_cert_file.path());
        std::env::set_var("TLS_CA_KEY_PATH", ca_key_file.path());

        let dir = tempfile::tempdir().unwrap();
        let cert_path = dir.path().join("node.crt");
        let key_path = dir.path().join("node.key");

        let provisioned =
            provision_node_cert_if_absent("new-node", &cert_path, &key_path, 365).unwrap();

        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");

        assert!(provisioned);
        assert!(cert_path.exists());
        assert!(key_path.exists());

        let cert_data = std::fs::read(&cert_path).unwrap();
        let mut reader = std::io::BufReader::new(cert_data.as_slice());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(certs.len(), 1);
    }

    #[test]
    fn provision_creates_when_cert_exists_but_key_missing() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let (_, cert_pem, key_pem) = make_ca();
        let ca_cert_file = write_temp(&cert_pem);
        let ca_key_file = write_temp(&key_pem);
        std::env::set_var("TLS_CA_CERT_PATH", ca_cert_file.path());
        std::env::set_var("TLS_CA_KEY_PATH", ca_key_file.path());

        // cert exists, key does not
        let cert_file = NamedTempFile::new().unwrap();
        let key_path = cert_file.path().with_extension("key.tmp");
        let _ = std::fs::remove_file(&key_path);

        let provisioned =
            provision_node_cert_if_absent("node", cert_file.path(), &key_path, 365).unwrap();

        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");
        assert!(provisioned);
        assert!(key_path.exists());
        let _ = std::fs::remove_file(&key_path);
    }

    #[test]
    fn provision_fails_without_env_vars() {
        let _g = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        std::env::remove_var("TLS_CA_CERT_PATH");
        std::env::remove_var("TLS_CA_KEY_PATH");

        let dir = tempfile::tempdir().unwrap();
        let cert_path = dir.path().join("node.crt");
        let key_path = dir.path().join("node.key");

        let result = provision_node_cert_if_absent("node", &cert_path, &key_path, 365);
        assert!(matches!(result, Err(PkiError::MissingCaCert)));
    }

    // ── CaHierarchy ───────────────────────────────────────────────────────

    #[test]
    fn hierarchy_generates_root_and_intermediate() {
        let h = CaHierarchy::generate().unwrap();
        assert!(h.root_cert_pem().contains("BEGIN CERTIFICATE"));
        assert!(h.intermediate_cert_pem().contains("BEGIN CERTIFICATE"));
    }

    #[test]
    fn hierarchy_root_and_intermediate_are_different_keys() {
        let h = CaHierarchy::generate().unwrap();
        assert_ne!(
            h.root().key().serialize_pem(),
            h.intermediate().key().serialize_pem()
        );
    }

    #[test]
    fn hierarchy_chain_pem_contains_both() {
        let h = CaHierarchy::generate().unwrap();
        let chain = h.chain_pem();
        let count = chain.matches("BEGIN CERTIFICATE").count();
        assert_eq!(count, 2, "chain should contain root + intermediate");
    }

    #[test]
    fn hierarchy_sign_node_cert() {
        let h = CaHierarchy::generate().unwrap();
        let issued = h.sign_node_cert("node-hier-1", 365).unwrap();
        assert!(issued.cert_pem.contains("BEGIN CERTIFICATE"));
        assert!(!issued.cert_der.as_ref().is_empty());
    }

    #[test]
    fn hierarchy_node_cert_signed_by_intermediate() {
        let h = CaHierarchy::generate().unwrap();
        let issued = h.sign_node_cert("node-hier-2", 365).unwrap();

        let mut reader = std::io::BufReader::new(h.intermediate_cert_pem().as_bytes());
        let inter_certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        assert_eq!(inter_certs.len(), 1);
        assert!(!inter_certs[0].as_ref().is_empty());
        assert!(!issued.cert_der.as_ref().is_empty());
    }

    #[test]
    fn hierarchy_intermediate_accepted_by_root_trust_store() {
        let h = CaHierarchy::generate().unwrap();

        let mut reader = std::io::BufReader::new(h.root_cert_pem().as_bytes());
        let root_certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        let root_der = root_certs.into_iter().next().unwrap();

        let mut root_store = rustls::RootCertStore::empty();
        root_store.add(root_der).unwrap();

        use rustls::server::WebPkiClientVerifier;
        let verifier = WebPkiClientVerifier::builder(std::sync::Arc::new(root_store)).build();
        assert!(verifier.is_ok(), "root cert accepted by WebPKI");
    }

    #[test]
    fn hierarchy_multiple_node_certs_different_keys() {
        let h = CaHierarchy::generate().unwrap();
        let c1 = h.sign_node_cert("node-a", 30).unwrap();
        let c2 = h.sign_node_cert("node-b", 30).unwrap();
        assert_ne!(c1.key_pem, c2.key_pem);
    }

    #[test]
    fn hierarchy_crl_signed_by_intermediate() {
        use crate::msp::crl_rfc5280::generate_crl_der;
        let h = CaHierarchy::generate().unwrap();
        let serials = vec![hex::encode([1u8; 8])];
        let der = generate_crl_der(&serials, h.intermediate(), 1, 7).unwrap();
        assert_eq!(der[0], 0x30);
    }

    #[test]
    fn hierarchy_debug_format() {
        let h = CaHierarchy::generate().unwrap();
        let dbg = format!("{h:?}");
        assert!(dbg.contains("Goya Ledger Intermediate CA"));
        assert!(dbg.contains(INTERNAL_CA_CN));
    }

    // ── certificatePolicies extension ──────────────────────────────

    #[test]
    fn cert_contains_certificate_policies_extension() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-policy", &ca, 365).unwrap();
        let der = issued.cert_der.as_ref();
        // OID 2.5.29.32 in DER = 55 1D 20
        let oid_bytes: &[u8] = &[0x55, 0x1D, 0x20];
        assert!(
            der.windows(3).any(|w| w == oid_bytes),
            "cert must contain certificatePolicies OID (2.5.29.32)"
        );
    }

    #[test]
    fn cert_contains_cps_uri() {
        let (ca, _, _) = make_ca();
        let issued = sign_node_cert("node-cps", &ca, 365).unwrap();
        let der = issued.cert_der.as_ref();
        let uri = b"https://goya.cl/pki/cp";
        assert!(
            der.windows(uri.len()).any(|w| w == uri),
            "cert must contain CPS URI"
        );
    }

    #[test]
    fn ca_cert_contains_policy_extension() {
        let (_, cert_pem, _) = make_ca();
        let mut reader = std::io::BufReader::new(cert_pem.as_bytes());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        let der = certs[0].as_ref();
        let oid_bytes: &[u8] = &[0x55, 0x1D, 0x20];
        assert!(
            der.windows(3).any(|w| w == oid_bytes),
            "CA cert must contain certificatePolicies OID"
        );
    }

    #[test]
    fn hierarchy_intermediate_contains_policy_extension() {
        let h = CaHierarchy::generate().unwrap();
        let mut reader = std::io::BufReader::new(h.intermediate_cert_pem().as_bytes());
        let certs: Vec<_> = rustls_pemfile::certs(&mut reader)
            .collect::<Result<_, _>>()
            .unwrap();
        let der = certs[0].as_ref();
        let uri = b"https://goya.cl/pki/cp";
        assert!(
            der.windows(uri.len()).any(|w| w == uri),
            "intermediate cert must contain CPS URI"
        );
    }

    #[test]
    fn renew_node_cert_produces_different_key() {
        let (ca, _, _) = make_ca();
        let orig = sign_node_cert("node-renew", &ca, 365).unwrap();
        let renewed = renew_node_cert("node-renew", &ca, 365).unwrap();
        assert_ne!(
            orig.key_pem, renewed.key_pem,
            "renewed cert must have fresh key"
        );
        assert!(renewed.cert_pem.contains("BEGIN CERTIFICATE"));
    }

    // ── MSP suspension ────────────────────────────────────────────

    #[test]
    fn msp_suspend_and_reinstate() {
        use crate::msp::Msp;
        let mut msp = Msp::new("msp1", "org1");
        let key = [42u8; 32];
        msp.root_public_keys.push(key);
        let serial = hex::encode(key);

        assert!(msp.validate_identity(&key).is_ok());

        msp.suspend(&serial).unwrap();
        assert!(msp.is_suspended(&serial));
        assert!(matches!(
            msp.validate_identity(&key),
            Err(crate::msp::MspError::Suspended { .. })
        ));

        msp.reinstate(&serial).unwrap();
        assert!(!msp.is_suspended(&serial));
        assert!(msp.validate_identity(&key).is_ok());
    }

    #[test]
    fn msp_cannot_suspend_revoked() {
        use crate::msp::Msp;
        let mut msp = Msp::new("msp1", "org1");
        let serial = hex::encode([1u8; 32]);
        msp.revoke(&serial);
        assert!(matches!(
            msp.suspend(&serial),
            Err(crate::msp::MspError::Revoked { .. })
        ));
    }

    #[test]
    fn msp_cannot_reinstate_revoked() {
        use crate::msp::Msp;
        let mut msp = Msp::new("msp1", "org1");
        let serial = hex::encode([1u8; 32]);
        msp.revoke(&serial);
        assert!(matches!(
            msp.reinstate(&serial),
            Err(crate::msp::MspError::Revoked { .. })
        ));
    }

    #[test]
    fn msp_revoke_clears_suspension() {
        use crate::msp::Msp;
        let mut msp = Msp::new("msp1", "org1");
        let serial = hex::encode([1u8; 32]);
        msp.suspend(&serial).unwrap();
        assert!(msp.is_suspended(&serial));
        msp.revoke(&serial);
        assert!(!msp.is_suspended(&serial));
    }

    #[test]
    fn qc_statements_der_natural_person() {
        let der = build_qc_statements_der(crate::pki_policy::CertProfileType::NaturalPerson);
        assert!(!der.is_empty());
        assert_eq!(der[0], 0x30, "must be SEQUENCE");
        let outer_len = der[1] as usize;
        assert_eq!(der.len(), 2 + outer_len, "length must match");
    }

    #[test]
    fn qc_statements_der_legal_person() {
        let der = build_qc_statements_der(crate::pki_policy::CertProfileType::LegalPerson);
        assert!(!der.is_empty());
        assert_eq!(der[0], 0x30);
    }

    #[test]
    fn qc_statements_der_web_auth() {
        let der = build_qc_statements_der(crate::pki_policy::CertProfileType::WebAuthentication);
        assert!(!der.is_empty());
        assert_eq!(der[0], 0x30);
    }

    #[test]
    fn qc_statements_profiles_produce_different_der() {
        let np = build_qc_statements_der(crate::pki_policy::CertProfileType::NaturalPerson);
        let lp = build_qc_statements_der(crate::pki_policy::CertProfileType::LegalPerson);
        let wa = build_qc_statements_der(crate::pki_policy::CertProfileType::WebAuthentication);
        assert_ne!(np, lp);
        assert_ne!(lp, wa);
        assert_ne!(np, wa);
    }

    #[test]
    fn qc_statements_extension_builds() {
        let ext = qc_statements_extension(crate::pki_policy::CertProfileType::NaturalPerson);
        // Verify it's a valid CustomExtension (doesn't panic)
        drop(ext);
    }

    #[test]
    fn qc_statements_cert_with_extension() {
        let (ca, _cert_pem, _key_pem) = make_ca();
        let mut params = CertificateParams::new(vec!["test-qc".to_string()]).unwrap();
        params
            .distinguished_name
            .push(DnType::CommonName, "test-qc");
        params.is_ca = IsCa::NoCa;
        params.custom_extensions.push(qc_statements_extension(
            crate::pki_policy::CertProfileType::NaturalPerson,
        ));
        let key_pair = KeyPair::generate().unwrap();
        let cert = params.signed_by(&key_pair, ca.cert(), ca.key()).unwrap();
        let pem = der_to_pem_cert(cert.der().as_ref());
        assert!(pem.contains("BEGIN CERTIFICATE"));
    }
}
